version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: strelog
      POSTGRES_PASSWORD: strelog
      POSTGRES_DB: strelogdb
    ports:
      - "5432:5432"
